/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoApiKeyImport } from './routes/no-api-key'
import { Route as IndexImport } from './routes/index'
import { Route as QueryQueryImport } from './routes/query.$query'

// Create/Update Routes

const NoApiKeyRoute = NoApiKeyImport.update({
  id: '/no-api-key',
  path: '/no-api-key',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QueryQueryRoute = QueryQueryImport.update({
  id: '/query/$query',
  path: '/query/$query',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/no-api-key': {
      id: '/no-api-key'
      path: '/no-api-key'
      fullPath: '/no-api-key'
      preLoaderRoute: typeof NoApiKeyImport
      parentRoute: typeof rootRoute
    }
    '/query/$query': {
      id: '/query/$query'
      path: '/query/$query'
      fullPath: '/query/$query'
      preLoaderRoute: typeof QueryQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/no-api-key': typeof NoApiKeyRoute
  '/query/$query': typeof QueryQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/no-api-key': typeof NoApiKeyRoute
  '/query/$query': typeof QueryQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/no-api-key': typeof NoApiKeyRoute
  '/query/$query': typeof QueryQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/no-api-key' | '/query/$query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/no-api-key' | '/query/$query'
  id: '__root__' | '/' | '/no-api-key' | '/query/$query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoApiKeyRoute: typeof NoApiKeyRoute
  QueryQueryRoute: typeof QueryQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoApiKeyRoute: NoApiKeyRoute,
  QueryQueryRoute: QueryQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/no-api-key",
        "/query/$query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/no-api-key": {
      "filePath": "no-api-key.tsx"
    },
    "/query/$query": {
      "filePath": "query.$query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
